rmdir /s /q .\.svn
rmdir /s /q .\docs\.svn
rmdir /s /q .\files\.svn
rmdir /s /q .\src\.svn
rmdir /s /q .\src\cowpatty-4.6\.svn
rmdir /s /q .\src\datacapture\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\google\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\google\code\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\google\code\distributedwpacracking\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\google\code\distributedwpacracking\master\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\java\com\google\code\distributedwpacracking\master\servlets\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\resources\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\webapp\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\src\main\webapp\WEB-INF\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\google\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\google\code\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\google\code\distributedwpacracking\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\google\code\distributedwpacracking\master\.svn
rmdir /s /q .\src\distributed-wpa-cracking-master\target\classes\com\google\code\distributedwpacracking\master\servlets\.svn